### ISSUE TITLE
Formatting is not working properly, --version is greyed out and few text are showing up in red

### ISSUE THREAD

**Issue by gmidha1** [redhat-solution-patterns/course-ui#1]
Hello There,

I am reporting this issue as formatting is not working properly as shown in the below screenshot
![Screenshot 2022-08-24 at 20 38 47](https://user-images.githubusercontent.com/110543061/186455283-810fdc5a-181d-46bc-96d4-a325ebd03d05.png)

--version is greyed out and few texts are showing up in red.

Here is the code for --version:
[.console-input]
[source,shell script]
```
oc version
make --version
git version
ansible --version 
ansible-galaxy --version 
ansible-galaxy collection list #the list should include kubernetes.core
```

Here is the code for red text:
[.console-input]
[source,shell script]
```
cd multicloud-gitops
git checkout odf
```

and

[.console-input]
[source,shell script]
```
git clone git@github.com:{username}/multicloud-gitops.git
```

Adding @kmacedovarela for this info.

Please help.

Thanks,
Gaurav

**Comment by jayachristina** [comment]
@gmidha1 is this still an issue please?

**Comment by jayachristina** [comment]
this is default behaviour and no fix is needed
