### ISSUE TITLE
Add MultiCloud GitOps with ODF to Solution Pattern menu

### ISSUE THREAD

**Issue by gmidha1** [redhat-solution-patterns/course-ui#3]
Hello there,

Please add MultiCloud GitOps with ODF to Solution Pattern menu.

Here is the repo link: https://github.com/gmidha1/solution-pattern-multicloud-gitops-odf
RHPDS workshop link: https://demo.redhat.com/catalog?search=odf&item=babylon-catalog-prod%2Fsandboxes-gpte.ocp4-multi-cloud-gitops-odf-bind.prod

Thank you.

**Comment by jayachristina** [comment]
This is complete
