### ISSUE TITLE
Add Solution Pattern: RedHat Openshift Service on AWS(ROSA)  to Solution Pattern menu

### ISSUE THREAD

**Issue by gmidha1** [redhat-solution-patterns/course-ui#5]
Hello there,

Please add Solution Pattern: RedHat Openshift Service on AWS(ROSA) to Solution Pattern menu.

Here is the repo link: https://github.com/gmidha1/solution-pattern-rosa

Thank you.

**Comment by gmidha1** [comment]
@btison / @jayachristina ,

Can you please help with this request.

**Comment by jayachristina** [comment]
This is complete

**Comment by jayachristina** [comment]
Closing the issue
